/**
 * Authoritative TS content data — embedded verbatim from the architecture.
 * This is the single source of truth for all copy on the site.
 */

export const TS_PHILOSOPHY = {
  headline: "TS — inspectable reasoning traces",
  subheadline:
    "Here is a small bounded reasoning system. Here are the traces. Here are the failures. Here is what changed from v3 to v10.",
  manifesto: [
    "TS-Reasoner is a bounded control loop, not a general intelligence claim.",
    "Every run emits candidate chains, local tension, global tension, and rejected alternatives.",
    "The useful artifact is the trace: what was accepted, what was repaired, and what failed.",
    "TensionLM is tested as a candidate proposer inside the verifier loop.",
    "CIG and TS-Codex-OS sit behind the trace contract as provenance and release-control infrastructure.",
    "Progress is measured by receipts, deltas, and visible failure modes.",
  ],
  os: {
    name: "TS-OS",
    description: "The dead-simple operating system for any thinking system.",
    loop: `while true:\n  Propagate()  // wave spreads activation (topological + semantic cosine)\n  Relax()      // decay toward base_strength\n  if tension too high:\n    Break()    // collapse weakest patterns\n    Evolve()   // spawn higher-stability nodes (LLM synthesis or manual vibe-code)`,
    directive:
      "Your only job: find the lowest-stability node and push activation (vibe-code) until it breaks. The OS converges everything else.",
  },
} as const;

export const WAVE_CYCLE_STEPS = [
  { step: 1, name: "Elect", description: "Select the strongest node by highest activation × stability score." },
  { step: 2, name: "Propagate", description: "Hybrid topological + embedding cosine spread — activation flows through edges weighted by semantic similarity." },
  { step: 3, name: "Relax + Normalize", description: "Decay all activations toward base_strength. Cap at 1.0. Prevent runaway excitation." },
  { step: 4, name: "Prune", description: "Remove edges with weight < 0.25. Low-confidence connections collapse." },
  { step: 5, name: "Merge", description: "Nodes with >50% topic overlap collapse into a single higher-stability node." },
  { step: 6, name: "Split", description: "Over-activated nodes (activation > 0.95, high internal tension) split into specialized children." },
  { step: 7, name: "Contradict", description: "Detect semantic contradictions across the graph. Resolve via stability vote — weaker claim loses." },
  { step: 8, name: "Tension", description: "Calculate global tension score. If too high → Break (collapse weakest pattern) or Evolve (spawn new node via LLM)." },
  { step: 9, name: "Save", description: "Incremental SQLite WAL write + snapshot to JSON fallback. Zero data loss on crash." },
] as const;

export const SELF_IMPROVEMENT_LOOP = {
  steps: [
    "High-confidence interaction traces collected during normal operation",
    "Traces formatted as Alpaca-style instruction dataset",
    "Unsloth 4-bit QLoRA fine-tuning on base model (hot-swappable)",
    "Validation: semantic similarity + task success rate must improve",
    "Rollback if validation fails — previous model restored instantly",
    "Hot-swap: new weights loaded with zero downtime",
  ],
  stack: "Unsloth + 4-bit QLoRA + PEFT + validation harness",
} as const;

export const MULTIMODAL_STACK = [
  { name: "faster-whisper", role: "Speech-to-text (offline, CPU/GPU)", type: "audio" },
  { name: "Piper TTS", role: "Text-to-speech (local neural voices)", type: "audio" },
  { name: "BLIP2", role: "Image captioning + visual understanding", type: "vision" },
] as const;

export const TECH_STACK = [
  { name: "Python 3.12", category: "runtime" },
  { name: "FastAPI", category: "api" },
  { name: "SQLite WAL", category: "storage" },
  { name: "Cytoscape.js", category: "visualization" },
  { name: "Chart.js", category: "visualization" },
  { name: "Rich TUI", category: "observability" },
  { name: "Unsloth 4-bit QLoRA", category: "ml" },
  { name: "faster-whisper", category: "ml" },
  { name: "BLIP2", category: "ml" },
  { name: "Piper TTS", category: "ml" },
] as const;

export const REPOS = [
  {
    id: "tensionlm",
    name: "TensionLM",
    description: "TensionLM: sigmoid tension instead of softmax attention, with public evidence boundaries, Path A repair tooling, and safetensors artifacts.",
    url: "https://github.com/BoggersTheFish/TensionLM",
    pinned: true,
    stability: 0.9,
    wave: 17,
    tags: ["llm", "tension", "evidence"],
  },
  {
    id: "ts-proof-ranker",
    name: "ts-proof-ranker",
    description: "Verifier-backed Horn proof-control ladder, published as Hugging Face artifacts v0-v4 plus matched tension-vs-softmax receipts.",
    url: "https://huggingface.co/BoggersTheFish/ts-proof-ranker-v4",
    pinned: true,
    stability: 0.86,
    wave: 17,
    tags: ["proof", "verifier", "receipts"],
  },
  {
    id: "boggerstheai",
    name: "BoggersTheAI",
    description: "The local TS-OS runtime: graph-wave reasoning, modular interfaces, tests, and an installable Python package.",
    url: "https://github.com/BoggersTheFish/BoggersTheAI",
    pinned: true,
    stability: 0.92,
    wave: 18,
    tags: ["core", "ai", "live"],
  },
  {
    id: "boggersthecig",
    name: "BoggersTheCIG",
    description: "Contextual Information Generator workbench for TS context, memory, and local automation experiments.",
    url: "https://github.com/BoggersTheFish/BoggersTheCIG",
    pinned: true,
    stability: 0.82,
    wave: 18,
    tags: ["context", "automation"],
  },
  {
    id: "tensionlm",
    name: "TensionLM",
    description: "Public tension-model experiment with a reproducible CPU runner and verifier bridge receipts.",
    url: "https://github.com/BoggersTheFish/TensionLM",
    pinned: true,
    stability: 0.78,
    wave: 17,
    tags: ["llm", "tension"],
  },
  {
    id: "goat-ts",
    name: "GOAT-TS",
    description: "Greatest Of All Time — Thinking System. The theoretical foundation and research notes.",
    url: "https://github.com/BoggersTheFish/GOAT-TS",
    pinned: true,
    stability: 0.85,
    wave: 8,
    tags: ["theory", "research"],
  },
  {
    id: "ts-core",
    name: "TS-Core",
    description: "Core graph engine: UniversalLivingGraph, WaveCycleRunner, and node/edge primitives.",
    url: "https://github.com/BoggersTheFish/TS-Core",
    pinned: true,
    stability: 0.88,
    wave: 10,
    tags: ["core", "engine"],
  },
  {
    id: "boggersmind",
    name: "BoggersTheMind",
    description: "Cognitive layer — long-term memory, episodic recall, and metacognition modules.",
    url: "https://github.com/BoggersTheFish/BoggersTheMind",
    pinned: true,
    stability: 0.78,
    wave: 9,
    tags: ["memory", "cognition"],
  },
  {
    id: "boggerspulse",
    name: "BoggersThePulse",
    description: "Real-time event stream and observability layer. The heartbeat of the system.",
    url: "https://github.com/BoggersTheFish/BoggersThePulse",
    pinned: false,
    stability: 0.72,
    wave: 11,
    tags: ["observability", "streaming"],
  },
  {
    id: "boggeros-alpha",
    name: "BoggersTheOS-Alpha",
    description: "First OS prototype. Experimental constraint-satisfaction kernel.",
    url: "https://github.com/BoggersTheFish/BoggersTheOS-Alpha",
    pinned: false,
    stability: 0.65,
    wave: 5,
    tags: ["os", "experimental"],
  },
  {
    id: "boggeros-beta",
    name: "BoggersTheOS-Beta",
    description: "Beta OS iteration with improved wave cycle and persistence layer.",
    url: "https://github.com/BoggersTheFish/BoggersTheOS-Beta",
    pinned: false,
    stability: 0.75,
    wave: 7,
    tags: ["os", "beta"],
  },
  {
    id: "site",
    name: "boggersthefish-site",
    description: "This site: public map for TS repos, model artifacts, and the current local-first automation surface.",
    url: "https://github.com/BoggersTheFish/boggersthefish-site",
    pinned: false,
    stability: 0.7,
    wave: 18,
    tags: ["site", "meta"],
  },
] as const;

export const SOCIAL_LINKS = [
  {
    id: "github",
    label: "GitHub",
    url: "https://github.com/BoggersTheFish",
    handle: "@BoggersTheFish",
    icon: "github",
    primary: true,
  },
  {
    id: "huggingface",
    label: "Hugging Face",
    url: "https://huggingface.co/BoggersTheFish",
    handle: "BoggersTheFish",
    icon: "external",
    primary: true,
    note: "TensionLM and proof-ranker model artifacts",
  },
  {
    id: "tensionlm-collection",
    label: "TensionLM Models",
    url: "https://huggingface.co/collections/BoggersTheFish/tensionlm-reasoning-line-6a0b3732559a93805439f8c2",
    handle: "TensionLM Reasoning Line",
    icon: "external",
    primary: false,
    note: "Current reasoning artifacts in order",
  },
  {
    id: "email",
    label: "Email",
    url: "mailto:boggersthefish@gmail.com",
    handle: "boggersthefish@gmail.com",
    icon: "mail",
    primary: true,
  },
  {
    id: "youtube",
    label: "YouTube",
    url: "https://youtube.com/@BoggersTheFish",
    handle: "@BoggersTheFish",
    icon: "youtube",
    primary: false,
    note: "Minecraft / OG Network archive",
  },
  {
    id: "instagram",
    label: "Instagram",
    url: "https://instagram.com/boggersthefish",
    handle: "@boggersthefish",
    icon: "instagram",
    primary: false,
  },
  {
    id: "threads",
    label: "Threads",
    url: "https://threads.net/@boggersthefish",
    handle: "@boggersthefish",
    icon: "at-sign",
    primary: false,
  },
  {
    id: "x",
    label: "X (Twitter)",
    url: "https://x.com/BoggersTheFish",
    handle: "@BoggersTheFish",
    icon: "twitter",
    primary: false,
  },
  {
    id: "chess",
    label: "Chess.com",
    url: "https://chess.com/member/BoggersTheFish",
    handle: "BoggersTheFish",
    icon: "crown",
    primary: false,
  },
] as const;

export const PUBLIC_RECEIPTS = [
  {
    id: "ts-reasoner-v2",
    title: "TS-Reasoner v10.0.0 — verifier-first runtime OS",
    claim: "A bounded runtime OS can route candidate events through policy contracts, replay, ledger, checkpoint/restore, and recovery while typed verifier support remains proof authority.",
    command: "python3 -m ts_reasoner.cli v10",
    artifact: "artifacts/runtime_os_receipt.json",
    limitation: "Runtime integrity is not claim truth; not a chatbot, theorem prover, or broad language-understanding claim.",
    link: "https://github.com/BoggersTheFish/TS-Reasoner-v0/blob/main/artifacts/runtime_os_receipt.json",
  },
  {
    id: "ts-reasoner-v09",
    title: "TS-Reasoner v0.9.0 — proof-chain gap closed",
    claim: "The existing small proof-chain failures now pass through explicit positive all/all bridge support.",
    command: "python3 scripts/evaluate_v09_proof_chains.py",
    artifact: "artifacts/v09_proof_chain_report.json",
    limitation: "Only positive universal all/all chains are covered.",
    link: "https://github.com/BoggersTheFish/TS-Reasoner-v0/blob/main/artifacts/v09_proof_chain_report.json",
  },
  {
    id: "tensionlm-runner",
    title: "TensionLM public CPU runner",
    claim: "A public Hugging Face checkpoint can be downloaded, loaded, and sampled from a CPU script.",
    command:
      'python3 scripts/run_public_tensionlm.py --repo-id BoggersTheFish/TensionLM-Curriculum-13M --prompt "If all mammals are animals and all whales are mammals then"',
    artifact: "scripts/run_public_tensionlm.py",
    limitation: "Raw narrow checkpoint; output quality is limited and not instruction tuned.",
    link: "https://github.com/BoggersTheFish/TensionLM/blob/main/scripts/run_public_tensionlm.py",
  },
  {
    id: "tensionlm-bridge",
    title: "TS-Reasoner + TensionLM export set",
    claim: "A small TensionLM-side export set can be verified with preserved failure reasons.",
    command: "python3 scripts/evaluate_tensionlm_export_set.py",
    artifact: "artifacts/tensionlm_export_set_report.json",
    limitation: "Exported candidate path only; model confidence remains metadata.",
    link: "https://github.com/BoggersTheFish/TS-Reasoner-v0/blob/main/docs/tensionlm_export_set_evaluation.md",
  },
  {
    id: "ts-codex-os",
    title: "TS-Codex-OS release-control inspection",
    claim: "A local project graph can emit status, next actions, and release-control receipts.",
    command: "python3 scripts/demo_ts_codex_os.py",
    artifact: "artifacts/release_receipt.json",
    limitation: "Local heuristic project substrate; not an autonomous coding agent.",
    link: "https://github.com/BoggersTheFish/TS-Codex-OS/blob/main/docs/receipts.md",
  },
  {
    id: "technical-tour",
    title: "20-minute technical tour",
    claim: "The public route can be inspected through a short tour: start route, proof receipt, TensionLM run, and limits.",
    command: "Read docs/technical_tour_20_min.md and run the listed commands",
    artifact: "docs/technical_tour_20_min.md",
    limitation: "Tour script only; the recording is separate from the runnable artifacts.",
    link: "https://github.com/BoggersTheFish/TS-Start-Here/blob/main/docs/technical_tour_20_min.md",
  },
  {
    id: "cig-provenance",
    title: "CIG provenance / contradiction handling",
    claim: "CIG stores claim provenance, confidence, bridge nodes, and heuristic contradiction signals.",
    command: 'python src/main.py --input "Alice supports the claim that gravity affects light." --no-llm',
    artifact: "memory/, graphs/, obsidian/TS-Knowledge-Vault/",
    limitation: "Extraction and contradiction detection are heuristic and incomplete.",
    link: "https://github.com/BoggersTheFish/BoggersTheCIG/blob/main/docs/FIRST_CONTACT.md",
  },
  {
    id: "proof-bank",
    title: "Proof-bank experiments",
    claim: "The CIG/TS engine can generate an inspectable proof-bank report from a prebuilt graph.",
    command: "python examples/generate_proof_report.py",
    artifact: "docs/proof_bank/TS-012-prebuilt-concept-graph.md",
    limitation: "Prebuilt deterministic graph; not a learned or formal proof system.",
    link: "https://github.com/BoggersTheFish/cig-ts-engine/blob/main/docs/proof_bank/TS-012-prebuilt-concept-graph.md",
  },
] as const;

export const NAV_LINKS = [
  { href: "/", label: "Home", section: "home" },
  { href: "/evidence", label: "Evidence", section: "evidence" },
  { href: "/about", label: "About", section: "about" },
  { href: "/ts-os", label: "TS-OS", section: "ts-os" },
  { href: "/projects", label: "Projects", section: "projects" },
  { href: "/receipts", label: "Receipts", section: "receipts" },
  { href: "/lab", label: "Lab", section: "lab" },
  { href: "/waves", label: "Waves", section: "waves" },
  { href: "/network", label: "Network", section: "network" },
] as const;

export const WAVE_LOG = [
  { wave: 1, name: "Seed", date: "local archive", status: "historical", description: "Early experiment marker; exact date needs a receipt." },
  { wave: 2, name: "Graph Primitives", date: "local archive", status: "historical", description: "Node/edge data structures and activation math; local archive claim." },
  { wave: 3, name: "Wave Runner", date: "local archive", status: "historical", description: "Early propagate/relax cycle; exact date needs a receipt." },
  { wave: 4, name: "SQLite Persistence", date: "local archive", status: "historical", description: "WAL-mode graph storage work; local archive claim." },
  { wave: 5, name: "OS Alpha", date: "local archive", status: "historical", description: "BoggersTheOS-Alpha prototype branch; treat as historical until receipt-synced." },
  { wave: 6, name: "LLM Integration", date: "local archive", status: "historical", description: "Ollama/LLaMA node synthesis experiments; local archive claim." },
  { wave: 7, name: "OS Beta", date: "local archive", status: "historical", description: "BoggersTheOS-Beta iteration; treat as historical until receipt-synced." },
  { wave: 8, name: "GOAT-TS", date: "public repo era", status: "verified-context", description: "Theory repo appears in the public timeline; exact project arc remains source-bound." },
  { wave: 9, name: "Memory Layer", date: "local archive", status: "historical", description: "BoggersTheMind memory experiments; local archive claim." },
  { wave: 10, name: "Core Engine", date: "public repo era", status: "verified-context", description: "TS-Core public branch exists; stronger claims need linked receipts." },
  { wave: 11, name: "Pulse + Observability", date: "local archive", status: "historical", description: "Dashboard/observability experiments; local archive claim." },
  { wave: 12, name: "Pages Island", date: "local archive", status: "historical", description: "Earlier site/runtime framing; live-instance and test-count claims require receipt sync." },
  { wave: 13, name: "Distributed Graph", date: "draft/local", status: "draft", description: "Planned or local-only branch; no public date claim without receipt." },
  { wave: 14, name: "Docker One-Click", date: "draft/local", status: "draft", description: "Planned or local-only branch; no public date claim without receipt." },
  { wave: 15, name: "WASM Port", date: "draft/local", status: "draft", description: "Planned or local-only branch; no public date claim without receipt." },
  { wave: 16, name: "Multi-Agent Coordination", date: "draft/local", status: "draft", description: "Planned or local-only branch; no public date claim without receipt." },
  { wave: 17, name: "Evidence Cleanup", date: "Current update", status: "current", description: "Public claim ledger, source cleanup, CPU repair artifact, and evidence-bounded wording." },
  { wave: 18, name: "External Replication", date: "next", status: "next", description: "Larger held-out TAC controls, Path A GPU run, and external benchmark receipts." },
] as const;

export const SITE_META = {
  title: "BoggersTheFish — TS Reasoning Receipts",
  description:
    "Small bounded TS reasoning systems with inspectable traces, tension receipts, controlled model comparisons, and visible failures.",
  url: "https://www.boggersthefish.com",
  author: "BoggersTheFish",
  twitter: "@BoggersTheFish",
  lastWave: "Current update label",
  currentWave: 17,
  waveName: "Evidence Cleanup",
  ogImage: "https://www.boggersthefish.com/og-image.svg",
} as const;
